### ISSUE TITLE
[PE-D][Tester B] Diagrams in DG is too small

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-1/tp#231] opened 2024-11-08 21:12 UTC
Expected: The diagram in the DG should be visible for wording to be clearly seen
Actual: The diagrams in the DG does not have standardised sizing

![image.png](https://raw.githubusercontent.com/Virusrwj223/ped/main/files/d4b884e1-9b24-4ada-b12a-28511500385e.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Virusrwj223/ped#14

**Comment by Gra7ityIC3** [comment] 2024-11-10 05:30
Duplicate of #188.

**Closed as completed by Gra7ityIC3** 2024-11-10 05:30 UTC
Labels: response.Accepted, duplicate
